networks:
  inception:
    driver: bridge
    name: inception

volumes:
  wp_data:
    driver: local
    name: wp_data
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress
  db_data:
    driver: local
    name: db_data
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
  portainer_data:
    name: portainer_data
    driver: local

secrets:
  db_password: 
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  ftp_password:
    file: ../secrets/ftp_password.txt


services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    restart: always
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    secrets:
      - db_password
      - credentials
    depends_on: [mariadb, redis]
    restart: always
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks: [inception]
    restart: always
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    networks: [inception]
    volumes: [wp_data:/var/www/html]
    secrets: [ftp_password]
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file: [.env]
    restart: always
  static-site:
    build: ./requirements/bonus/static-site
    image: static-site
    container_name: static-site
    networks: [inception]
    ports:
      - "8080:8080"
    restart: always
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks: [inception]
    ports:
      - "8081:8081"
    depends_on: [mariadb]
    restart: always
  portainer:
    build: ./requirements/bonus/portainer
    image: portainer
    container_name: portainer
    networks: [inception]
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
