# tells vsftpd to run in standalone mode
listen=YES
# disables anonymous (no-login) FTP access
anonymous_enable=NO
# allows real system users
local_enable=YES
# allows uploads/modifications
write_enable=YES
# locks every logged-in user's view to just local_root
chroot_local_user=YES
# sets that locked-in root directory to the same path WordPress's files live at
local_root=/var/www/html

allow_writeable_chroot=YES
# turns on FTP's passive mode == the server tells the client which port to use for the actual data transfer
pasv_enable=YES
# the specific range of ports passive-mode data transfers are allowed to use
pasv_min_port=21100
pasv_max_port=21110
pasv_address=${DOMAIN_NAME}
